### ISSUE TITLE
更换UA更方便

### ISSUE THREAD

**Issue by 11yiyang** [magicdawn/weread-spy#1]
使用Kindle UA可以更加方便生成epub
Mozilla/5.0 (X11; U; Linux armv7l like Android; en-us) AppleWebKit/531.2+ (KHTML, like Gecko) Version/5.0 Safari/533.2+ Kindle/3.0+ 

使用该UA在网页访问微信读书是kindle页面，文字图片都可以复制，源代码都有

**Comment by magicdawn** [comment]
现在是依赖Vue的trick __vue__, 可以拿到 vue store 里面的文字图片等等
失效再说.
