### ISSUE TITLE
下完的书提示正常，但是没有内容

### ISSUE THREAD

**Issue by wjjc1017** [magicdawn/weread-spy#12]
<img width="157" alt="image" src="https://user-images.githubusercontent.com/36215938/197529047-9fe43a70-2376-4ae1-8617-97b29a0a080d.png">

下载提示正常，但是无法看到书的内容，只能看到目录，麻烦看看能修复一下么，谢谢

**Comment by xiel0325** [comment]
+1

**Comment by lieguoqingcheng** [comment]
+1

**Comment by aibot88** [comment]
+2, json文件长这样
![Uploading 111.png…]()

**Comment by magicdawn** [comment]
fixed in v0.4.0
