### ISSUE TITLE
输入y，浏览器关闭，同时报错

### ISSUE THREAD

**Issue by karpoul** [magicdawn/weread-spy#16]
1. 安装好工具后，执行`weread-spy one`，进行到最后一步，输入`y`后
2. 浏览器关闭，且报错。如图
<img width="2232" alt="iShot_2023-01-15_16 46 31" src="https://user-images.githubusercontent.com/7089304/212532397-c042eb92-e067-4403-82b8-62d367fdba35.png">

**Comment by HaaiSo** [comment]
同样的错误

**Comment by magicdawn** [comment]
无法复现.
