### ISSUE TITLE
图书内容被加密了，下载的书显示Object

### ISSUE THREAD

**Issue by Geralt-TYH** [magicdawn/weread-spy#17]
json文件中的内容像是被加密了
![image](https://user-images.githubusercontent.com/16754661/213338707-b3b3278e-0cd5-4738-9d47-0795ee38764a.png)
文件中之显示Object，目录正常
![image](https://user-images.githubusercontent.com/16754661/213338825-b048d182-5d2f-47fe-ba83-dac14b98f271.png)
期待大佬解决

**Comment by hiifong** [comment]
我这里也是
![image](https://user-images.githubusercontent.com/89133723/216524597-2672d501-be10-4b0c-a471-5a0712dc9d96.png)

**Comment by ouyangzh-CN** [comment]
遇到同样的问题

**Comment by futuping** [comment]
我也是

**Comment by magicdawn** [comment]
fixed in v0.4.0
