### ISSUE TITLE
书籍下载不完整

### ISSUE THREAD

**Issue by Swain9** [magicdawn/weread-spy#19]
有些书籍章节很长， 每个章节只能下载第一页的内容，需要点下一页才能看到

**Comment by magicdawn** [comment]
链接

**Comment by karpoul** [comment]
无内容，内容全是[Object]
我已购买的书籍链接：https://weread.qq.com/web/bookDetail/c5832da07204e285c581cd9

**Comment by shaderein** [comment]
需要翻页的书 如https://weread.qq.com/web/bookDetail/ead32510813ab7c1dg010ece 第一章分了两页 @magicdawn

**Comment by lj1998008** [comment]
> 链接

比如这个：https://weread.qq.com/web/bookDetail/ead32510813ab7c1dg010ece
这个的第一章，分了2页，只能下到第1页的

**Comment by lj1998008** [comment]
比如这个：https://weread.qq.com/web/bookDetail/ead32510813ab7c1dg010ece
这个的第一章，分了2页，只能下到第1页的
求大佬升级 @magicdawn
