### ISSUE TITLE
章节数过多时，会显示堆内存不足

### ISSUE THREAD

**Issue by lanyangyang1999** [magicdawn/weread-spy#21]
当我下载《罗辑思维荐书集锦（套装共24册）》尤瓦尔·赫拉利等 | 微信读书
https://weread.qq.com/book-detail?type=1&senderVid=320541134&v=f903217072525e4bf9018be&wtheme=white&wfrom=app&wvid=320541134&scene=bottomSheetShare
章节id到714时，会报错，显示堆内存不足，不知道是不是所有内容较多的书都报错
报错信息如下：
<--- Last few GCs --->

[19003:0x55740cc6be90]  1266761 ms: Scavenge (reduce) 2046.6 (2068.9) -> 2046.4 (2069.4) MB, 188.2 / 0.0 ms  (average mu = 0.973, current mu = 0.938) allocation failure; 
[19003:0x55740cc6be90]  1267409 ms: Mark-sweep (reduce) 2047.0 (2069.4) -> 2046.8 (2070.2) MB, 645.4 / 0.0 ms  (+ 9.0 ms in 43 steps since start of marking, biggest step 4.4 ms, walltime since start of marking 1429 ms) (average mu = 0.951, current mu = 0.

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0x7fe3a95f103c node::Abort() [/lib/x86_64-linux-gnu/libnode.so.108]
 2: 0x7fe3a94e72f8  [/lib/x86_64-linux-gnu/libnode.so.108]
 3: 0x7fe3a996207a v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/lib/x86_64-linux-gnu/libnode.so.108]
 4: 0x7fe3a9962437 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/lib/x86_64-linux-gnu/libnode.so.108]
 5: 0x7fe3a9b4af19  [/lib/x86_64-linux-gnu/libnode.so.108]
 6: 0x7fe3a9b610e3 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/lib/x86_64-linux-gnu/libnode.so.108]
 7: 0x7fe3a9b3c236 v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/lib/x86_64-linux-gnu/libnode.so.108]
 8: 0x7fe3a9b3d5e7 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/lib/x86_64-linux-gnu/libnode.so.108]
 9: 0x7fe3a9b1c526 v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/lib/x86_64-linux-gnu/libnode.so.108]
10: 0x7fe3a9b14568 v8::internal::FactoryBase<v8::internal::Factory>::AllocateRawWithImmortalMap(int, v8::internal::AllocationType, v8::internal::Map, v8::internal::AllocationAlignment) [/lib/x86_64-linux-gnu/libnode.so.108]
11: 0x7fe3a9b169fe v8::internal::FactoryBase<v8::internal::Factory>::NewRawOneByteString(int, v8::internal::AllocationType) [/lib/x86_64-linux-gnu/libnode.so.108]
12: 0x7fe3a9f8317a v8::internal::IncrementalStringBuilder::Extend() [/lib/x86_64-linux-gnu/libnode.so.108]
13: 0x7fe3a9f83346 v8::internal::IncrementalStringBuilder::AppendString(v8::internal::Handle<v8::internal::String>) [/lib/x86_64-linux-gnu/libnode.so.108]
14: 0x7fe3a9f3721b v8::internal::Runtime_RegExpReplaceRT(int, unsigned long*, v8::internal::Isolate*) [/lib/x86_64-linux-gnu/libnode.so.108]
15: 0x7fe3a98723b9  [/lib/x86_64-linux-gnu/libnode.so.108]
已放弃 (核心已转储)

![截图 2023-04-25 14-32-37](https://user-images.githubusercontent.com/100829491/234193376-58355db9-a6be-4563-9407-1698e1417a12.png)

**Comment by lanyangyang1999** [comment]
还有一个问题前面也有人报了，就是如果一章特别长，分了页的话，只能爬取第一页的，后面的内容爬不到。

**Comment by magicdawn** [comment]
自己酌情调整

```
# old space 改成 8G
NODE_OPTIONS='--max_old_space_size=8192' weread-spy
```
