### ISSUE TITLE
老问题，无法解决

### ISSUE THREAD

**Issue by lj1998008** [magicdawn/weread-spy#29]
比如这个：https://weread.qq.com/web/bookDetail/ead32510813ab7c1dg010ece
这个的第一章，分了2页，只能下到第1页的

这是个硬伤，求大佬解决

**Comment by magicdawn** [comment]
![image](https://github.com/magicdawn/weread-spy/assets/4067115/8d73a103-2964-45e7-bdfc-d920ff095853)
