### ISSUE TITLE
下载报错，大佬

### ISSUE THREAD

**Issue by Adver23** [magicdawn/weread-spy#33]
下载报错，大佬^_^
![50932568-1BD1-4CC9-9551-4C7FA5ECBAC6](https://github.com/magicdawn/weread-spy/assets/131567072/b83df971-5260-424b-8b6a-d4fb4f6c270e)

**Comment by xyw19870905** [comment]
我也碰到了同样的问题，坐等大佬更新解决

**Comment by magicdawn** [comment]
r
