### ISSUE TITLE
chapter css 重复

### ISSUE THREAD

**Issue by ctaoist** [magicdawn/weread-spy#39]
![image](https://github.com/magicdawn/weread-spy/assets/14012127/cd65abbd-e38d-4d0b-8c95-3108814bd4bf)

这些css的内容其实是一模一样的，希望能够优化一下，只保留一个

**Comment by Adver23** [comment]
> 

为什么你的还能跑😂

**Comment by ctaoist** [comment]
> > 
> 
> 为什么你的还能跑😂

啊？你们都不能运行吗

**Comment by magicdawn** [comment]
not interested. 而且不能保证所有书籍都一致
