### ISSUE TITLE
你好，又有两个问题

### ISSUE THREAD

**Issue by End-Satan** [magicdawn/weread-spy#4]
第一个，我要是要把多本书下载到本地，请求过多就会被禁止访问，请问有没有延时？
第二个，就是每次下载书后生成电子书那一步就卡住了，很多本书都是这样。卡在这一步。比如这一本。-https://weread.qq.com/web/reader/a2232dc05e4e56a22f0a95a
![2](https://user-images.githubusercontent.com/17049937/178347176-00a3781a-1368-4a57-ae60-b46f40c29300.png)

**Comment by magicdawn** [comment]
这个后面就是在下载图片, 识别图片类型, 之前下载没加超时,可能会卡在那里, 最新代码有超时了.
P.S 已发布到 npm, 全局安装即可, 最新 v0.1.1

```
pnpm add weread-spy -g
```

**Comment by magicdawn** [comment]
禁止访问这个看你使用频次吧, 我没遇到过.

**Comment by magicdawn** [comment]
use v0.2.0 

```sh
# 切换章节间隔 1000 ms
$ weread-spy one --interval 1000
```

dl 命令也有 `--interval`
