### ISSUE TITLE
下载出错，希望大佬可以继续维护

### ISSUE THREAD

**Issue by ZhengJieClassmate** [magicdawn/weread-spy#40]
报错信息如下：
``
PS C:\Users\inssu> weread-spy one
ua = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

当前浏览链接像是一本书:
   [url]: https://weread.qq.com/web/reader/e1932d70813ab82e7g014f5b
 [title]: 海绵阅读法：如何吸收一本书的精华-李小墨-微信读书
? 是否下载:  (Y/n)

当前浏览链接像是一本书:
   [url]: https://weread.qq.com/web/reader/e1932d70813ab82e7g014f5b?
 [title]: 海绵阅读法：如何吸收一本书的精华-李小墨-微信读书
? 是否下载:  Yes
file:///C:/Users/inssu/AppData/Local/Yarn/Data/global/node_modules/puppeteer-core/lib/esm/puppeteer/common/WaitTask.js:56
                void this.terminate(new TimeoutError(`Waiting failed: ${options.timeout}ms exceeded`));
                                    ^

TimeoutError: Waiting failed: 30000ms exceeded
    at Timeout.<anonymous> (file:///C:/Users/inssu/AppData/Local/Yarn/Data/global/node_modules/puppeteer-core/lib/esm/puppeteer/common/WaitTask.js:56:37)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
``

**Comment by champkeh** [comment]
欢迎使用这个项目 https://weread.deno.dev/

**Comment by magicdawn** [comment]
0.7.5
