### ISSUE TITLE
有些书抓完文本，在生成的时候报错

### ISSUE THREAD

**Issue by cnctx** [magicdawn/weread-spy#41]
免费书f1132f80813ab821eg018540，可以测试一下。

**Comment by champkeh** [comment]
我也写了一个类似的项目，只不过目前只支持下载 html 格式的，其他格式后续会慢慢开发，欢迎使用。
https://weread.deno.dev/detail.html?bookId=3300070708

我用你的这个例子(f1132f80813ab821eg018540)试了一下，是可以正常下载的

**Comment by magicdawn** [comment]
https://res.weread.qq.com/wrepub/CB_3300070708_83%28The_Earth_Through_Time%29.png
地址 404了, will fix in next patch version.

**Comment by magicdawn** [comment]
++++ 这本书的原始 html 有些问题

![image](https://github.com/magicdawn/weread-spy/assets/4067115/2037b7ee-91ab-4e41-94b1-1690f766e3a0)

epubcheck 会报错, 因为书本身没有这个 id=`acqy4`, lint 报错是符合期望的, 不影响 epub 阅读.
