### ISSUE TITLE
weread-spy的命令行

### ISSUE THREAD

**Issue by smilingpoplar** [magicdawn/weread-spy#6]
- `weread-spy dl -u <url>` 无法启动，`if (!justLaunch || !url) {`有误？
- `weread-spy gen -u <url>`不指定id无法生成，找不到id，读的map为空？

**Comment by magicdawn** [comment]
没问题.

**Comment by smilingpoplar** [comment]
按readme的分布调用命令行，是有上述小问题的
```
weread-spy dl -u <url> 下载电子书信息
weread-spy gen -u <url> 根据下载的信息, 生成电子书
```
