### ISSUE TITLE
获取章节卡住，刷新页面抛出异常

### ISSUE THREAD

**Issue by Colyn2022** [magicdawn/weread-spy#8]
在获取一些页面比较多的书籍的时候，微信读书会显示书籍页面获取失败，点击刷新后程序会抛出异常，然后退出。
![image](https://user-images.githubusercontent.com/109046933/188046677-69819d00-b222-4534-9dc0-1f56faba3cbe.png)

**Comment by magicdawn** [comment]
use v0.2.0 

```sh
# 切换章节间隔 1000 ms
$ weread-spy one --interval 1000
```

dl 命令也有 `--interval`
